import type { Delivery, Stage } from "@/lib/types";

/** Build a Delivery with sane defaults; override only what a test cares about. */
export function mkDelivery(over: Partial<Delivery> = {}): Delivery {
  const now = new Date().toISOString();
  return {
    id: Math.random().toString(36).slice(2),
    order_no: 1000,
    stage: "draft" as Stage,
    rejected_reason: null,
    redelivery_of: null,
    redelivery_reason: null,
    prepared_status: null,
    status_temp: null,
    order_type: "Delivery",
    store: "McAllen",
    po2: null,
    so_num: null,
    invoice_num: null,
    input_date: "2026-07-15",
    input_time: "0900",
    delivery_date: "2026-07-20",
    pickup_name: null,
    pickup_address: null,
    pickup_duration: null,
    delivery_fee: null,
    est_pallets: null,
    actual_pallets: null,
    assigned_driver: null,
    delivery_duration: null,
    delivery_name: null,
    delivery_address: null,
    delivery_windows: null,
    account: null,
    contact: null,
    delivery_phone: null,
    delivery_notes: null,
    route_miles: null,
    route_duration: null,
    route_provider: null,
    route_traffic: null,
    pod_received_by: null,
    pod_signature: null,
    pod_delivered_at: null,
    photos: null,
    pickup_lat: null,
    pickup_lng: null,
    pickup_gps_at: null,
    pod_lat: null,
    pod_lng: null,
    pod_accuracy: null,
    delivery_lat: null,
    delivery_lng: null,
    delivery_pin_source: null,
    created_by: "u-sales",
    approved_by: null,
    approved_at: null,
    created_at: now,
    updated_at: now,
    ...over,
  };
}
